### ISSUE TITLE
Please add a level  reward system

### ISSUE THREAD

**Issue by AriaFantom** [chxlls/discordleveling#1]

**Comment by chxlls** [comment]
Hey. Sorry, I don't update this anymore. I put it on here for others to explore it and use it how they want. I might end up doing it if it gets requested enough but for now, maybe not. I do appreciate your interest in my repo though.

**Comment by ghost** [comment]
This repository that I made does have that feature: https://github.com/discord-custom-bots/discord-leveling-bot

**Comment by ghost** [comment]
Made it public again: https://github.com/hyphonz-bots/discord-leveling-bot
