### ISSUE TITLE
Leaderboard levels/messages

### ISSUE THREAD

**Issue by ArticHorse** [chxlls/discordleveling#4]
Every time, I run the command I get the error, TypeError: db.startsWith is not a function.

Could someone help me fix this?

**Comment by jigr391** [comment]
Quick.db removed that feature, so the solution is to install version 7.0.0-b21 by doing npm i quick.db@7.0.0-b21

**Comment by ArticHorse** [comment]
I hate to be stupid but now I have,

Error: Cannot find module '../build/better_sqlite3.node'

**Comment by ghost** [comment]
Most other bot repositories aren't working, which is why I made another one: https://github.com/discord-custom-bots/discord-leveling-bot

**Comment by ghost** [comment]
That repo is private for now rip. Will revive soon.

**Comment by ghost** [comment]
Made it public again: https://github.com/hyphonz-bots/discord-leveling-bot
